from games.flash import GameFlash
from games.dodge import GameDodge
from games.spot_it import GameSpotIt
from games.archery import GameArchery
from games.traffic import GameTrafficRider
from games.memory import GameMemoryPuzzle
from games.block_drop import GameBlockDrop
from games.sky_dash import GameSkyDash
from games.find_secret import GameFindSecret
from games.color_chaos import GameColorChaos
from games.neon_rush import GameNeonRush